### PR TITLE
Fix(InputItem): onChange bug (close #3026)

### LINKED ISSUE #3026: 2.2.7版本更新后，InputItem onChange事件无法监听。
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zhang504988670/pen/QzqQBe](https://codepen.io/zhang504988670/pen/QzqQBe)

### Steps to reproduce
在输入框内输入内容，调用onChange事件，渲染setState方法。

### What is expected?
能够正常调用onChange事件

### What is actually happening?
onChange事件不触发。

| Environment | Info |
|---|---|
| antd | 2.2.7 |
| React | React16.7.0 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

### PR DESCRIPTION
**Pull request by zack24q**
close #3026 

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/3027)

### CODE REVIEW

**Comment by ziluo** [comment]
+1

File: components/input-item/index.tsx [hunk 1]
```diff
@@ -132,6 +132,11 @@ class InputItem extends React.Component<InputItemProps, any> {
       default:
         break;
     }
+
+    const { onChange } = this.props;
+    if (onChange) {
+      onChange(ctrlValue);
```
Comment (likezero) [inline components/input-item/index.tsx]: 参考下原来的实现
https://github.com/ant-design/ant-design-mobile/pull/2854/files#diff-da561ee58a9d0bf6841793d9067364a5L132
