### PR TITLE
fix: pass getContainer down to popup

### LINKED ISSUE #6455: CalendarPicker inside custom container
### Version of antd-mobile

5.33.0

## Support getContainer in CalendarPicker

As a developer who keeps micro frontends inside shadow dom I want to render calendar picker inside the shadow dom. But now it is not possible. 

### Solution

Pass the `getContainer` property down to the Popup component [here](https://github.com/ant-design/ant-design-mobile/blob/master/src/components/calendar-picker/calendar-picker.tsx#L101). The popup already supports it.

### PR DESCRIPTION
**Pull request by madiyetov**
resolve #6455

it is needed to render the CalendarPicker inside the Shadow DOM

### CODE REVIEW

File: src/components/calendar-picker/calendar-picker.tsx [hunk 1]
```diff
@@ -25,6 +26,7 @@ export type CalendarPickerProps = CalendarPickerViewProps & {
   closeOnMaskClick?: boolean
   onClose?: () => void
   onMaskClick?: () => void
+  getPopupContainer?: GetContainer
```
Comment (zombieJ) [inline src/components/calendar-picker/calendar-picker.tsx:29]: `getContainer` instead of `getPopupContainer`

**Review by zombieJ — APPROVED** [review]
