### PR TITLE
fix: textareaitem clear when uncontrolled

### LINKED ISSUE #2131: 使用TextareaItem 多行输入 clear 属性不生效

### PR DESCRIPTION
**Pull request by zhang740**
close #2131

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

---
This change is [Reviewable](https://reviewable.io/reviews/ant-design/ant-design-mobile/2133)

### CODE REVIEW

File: components/textarea-item/index.tsx [hunk 1]
```diff
@@ -197,7 +211,7 @@ export default class TextareaItem extends React.Component<TextareaItemProps, Tex
             ref={el => this.textareaRef = el}
             {...lengthCtrlProps}
             {...otherProps}
-            {...valueProps}
+            value={value}
```
Comment (paranoidjk) [inline components/textarea-item/index.tsx]: 这一行相当于底层的原生 textarea 固定使用受控模式了

File: components/textarea-item/index.tsx [hunk 2]
```diff
@@ -197,7 +211,7 @@ export default class TextareaItem extends React.Component<TextareaItemProps, Tex
             ref={el => this.textareaRef = el}
             {...lengthCtrlProps}
             {...otherProps}
```
Comment (paranoidjk) [inline components/textarea-item/index.tsx]: 这一行 otherProps 里面没有把 defaultValue 过滤掉？
