### PR TITLE
fix(ImageUploader): revokeObjectURL while file change

### LINKED ISSUE #5813: ImageUpload 删除图片
### Version of antd-mobile

5.25.1

### Operating system and its version

Others

### Browser and its version

PC Chrome:  107.0.5304.107

### Sandbox to reproduce

https://codesandbox.io/s/lthlhj?file=/app.tsx&resolutionWidth=375&resolutionHeight=700

### What happened?

复现环境：
官方demo(限制图片数量)  http://ant-design-mobile.antgroup.com/zh/components/image-uploader#%E5%B1%9E%E6%80%A7
问题：上传多张图片时，若不按倒序删除，会出现最后一张图片展示错误；如上传了【1，2，3】,先删除1或者2会导致图片3展示失败

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by IronKinoko**
fix #5813

### CODE REVIEW

**Review by zqran — DISMISSED** [review]

File: src/components/image-uploader/preview-item.tsx [hunk 1]
```diff
@@ -32,11 +32,11 @@ const PreviewItem: FC<Props> = props => {
     return ''
   }, [url, file])
 
-  useLayoutEffect(() => {
+  useEffect(() => {
     return () => {
-      URL.revokeObjectURL(src)
+      if (file) URL.revokeObjectURL(src)
```
Comment (zombieJ) [inline src/components/image-uploader/preview-item.tsx:37]: 来个测试用例？

**Review by miracles1919 — APPROVED** [review]

**Review by zombieJ — APPROVED** [review]
